

export default defineEventHandler(async ev=>{
    return {
        titles:['user info','traffic','User limitation','Contact info','Date','status','operation'],
        rows:[
            {
                username:'hooman_77',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'ali_88',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'reza-90',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'reza_09',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'arian',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'maryam',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'maryam',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'maryam',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'maryam',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'maryam',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'mahdi',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'arash',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'hooman_77',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
            {
                username:'hooman_77',
                password:'12345667',
                traffic:'Unlimited',
                usedVolume:0,
                userLimitation:1,
                contactInfo:'09981929653',
                date:{
                    registered:'02-05-2023',
                    expired:'02-05-2023'
                },
                active:true
            },
        ]
    }




})